name: Spidy File Ztream Bot
on:
  workflow_dispatch:
  schedule:
    - cron:  '0 */6 * * *'
jobs:
  run-sync-service:
    runs-on: ubuntu-latest
    steps:
      - name: Downloading the Script
        run: |
          wget -qq ${{ secrets.FILEZTREAM}}
      - name: Permission
        run: |
           chmod 777 tgztream.sh
      - name: Running the Script
        run: |
           sudo bash tgztream.sh
           
