name: Spidy Mirror Bot
on:
  workflow_dispatch:
jobs:
  run-sync-service:
    runs-on: ubuntu-latest
    steps:
      - name: Downloading the Script
        run: |
          wget -qq ${{secrets.MLTB}}
      - name: Permission
        run: |
           chmod 777 mltb.sh
      - name: Running the Script
        run: |
           sudo bash mltb.sh
