name: Mirleechx Mirror Bot
on:
  workflow_dispatch:
  schedule:
    - cron:  '30 6 * * *'
jobs:
  run-sync-service:
    runs-on: ubuntu-latest
    steps:
      - name: Downloading the Script
        run: |
          wget https://gist.github.com/BlackFoxy616/00509ef05bab1227061dfab15b050a86/raw/mirror.sh
      - name: Permission
        run: |
           chmod 777 mirror.sh
      - name: Running the Script
        run: |
           ./mirror.sh
