name: WZML-X Mirror Bot
on:
  workflow_dispatch:
  schedule:
    - cron:  '10 */6 * * *'
jobs:
  run-sync-service:
    runs-on: ubuntu-latest
    steps:
      - name: Downloading the Script
        run: |
          wget -qq ${{ secrets.WZMLX}}
      - name: Permission
        run: |
           chmod 777 wzmlx.sh
      - name: Running the Script
        run: |
           ./wzmlx.sh
           
