name: WZML-X Mirror Bot
on:
  workflow_dispatch: 
  schedule:
    - cron:  '0 */6 * * *'
jobs:
  run-sync-service:
    runs-on: ubuntu-latest
    steps:
      - name: Downloading the Script
        run: |
          wget -qq ${{ secrets.WZMLX}}
      - name: Permission
        run: |
           chmod 777 wzml.sh
      - name: Running the Script
        run: |
           sudo bash wzml.sh
           
