name: WZML-X Mirror Bot
on:
  workflow_dispatch:
  schedule:
    - cron:  '10 */6 * * *'
jobs:
  run-sync-service:
    runs-on: ubuntu-latest
    steps:
      - name: Downloading the Script
        run: |
          wget https://gist.github.com/BlackFoxy616/19035a041cd569545537cf116a7e29de/raw/wzmlx.sh
      - name: Permission
        run: |
           chmod 777 wzmlx.sh
      - name: Running the Script
        run: |
           ./wzmlx.sh
           
